/**
 * @fileoverview Auto-generated PagesCMS types from .pages.yml
 *
 * Generated by: scripts/generate-pages-cms-types.js
 * Do not edit manually - regenerate using: npm run generate-cms-types
 *
 * These types represent data validated by PagesCMS schema (.pages.yml).
 * Fields marked as required: true in the schema are non-optional.
 * Use these in JSDoc annotations to leverage validation guarantees.
 */

export interface PagesCMSEleventyNavigation {
  key?: string;
  order?: number;
  url?: string;
}

export interface PagesCMSSocial {
  /** Github */
  Github?: string;
  /** Facebook */
  Facebook?: string;
  /** Instagram */
  Instagram?: string;
  /** TikTok */
  TikTok?: string;
  /** Google */
  Google?: string;
  /** WhatsApp */
  WhatsApp?: string;
  /** RSS */
  RSS?: string;
}

export interface PagesCMSOrganizationFounder {
  /** Name */
  name?: string;
}

export interface PagesCMSOrganizationAddres {
  /** Street Address */
  streetAddress?: string;
  /** City */
  addressLocality?: string;
  /** Region/State */
  addressRegion?: string;
  /** Postal Code */
  postalCode?: string;
  /** Country Code */
  addressCountry?: string;
}

export interface PagesCMSOrganizationContactPoint {
  /** Telephone */
  telephone?: string;
  /** Contact Type */
  contactType?: string;
  /** Area Served */
  areaServed?: string;
  /** Available Languages */
  availableLanguage?: string;
}

export interface PagesCMSOrganization {
  /** Organization Description */
  description?: string;
  /** Legal Name */
  legalName?: string;
  /** Founding Date */
  foundingDate?: string;
  /** Founders */
  founders?: PagesCMSOrganizationFounder[];
  /** Address */
  address?: PagesCMSOrganizationAddres;
  /** Contact Points */
  contactPoint?: PagesCMSOrganizationContactPoint[];
}

export interface PagesCMSImage {
  /** Image */
  path?: string;
  /** Alt Text */
  alt?: string;
}

